### PR TITLE
Let workspace private and personal by default for all user

### PR DESCRIPTION
**Pull request by hghandri**
Issue: https://github.com/aws-samples/aws-genai-llm-chatbot/issues/227

Implement private workspace, every user create a workspace now is only private and not shareable with other user.
This feature implement a new DynamoBD table handle policies on top of Workspace Dynamodb table.
This implementation could facilitate sharing workspaces between users with writeable / readable policy  option through sharing process like Google Drive

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by massi-ang** [comment]
Thanks for submitting this PR. Is this changing all Workspaces to private to the user?

**Comment by hghandri** [comment]
Yes by default, all workspace will be private.
If we go ahead of this feature we could add interface to set if we want to open publicly the workspace or for some people ( example fetch a user from cognito )

**Comment by massi-ang** [comment]
As this is a breaking change, we should either think about an opt-in/out settings or the possibility to set workspaces as public/private and retain all existing workspaces as public.

**Comment by hghandri** [comment]
I will do a migration script to let all existing workspace public.

On further in case the workspace does not have owner ( legacy workspace ) the first one who will set through interface that the workspace is private then he will became the owner of this workspace for ever.

What do you think ?

**Comment by hghandri** [comment]
I closed this PR and opened a new one with more impact.

**Pull request closed without merging**
